# Generated by Django 5.2.17 on 2026-09-24 05:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientAccountVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_hash', models.CharField(max_length=64, unique=True)),
                ('phone_number', models.CharField(max_length=24)),
                ('code_hash', models.CharField(blank=True, max_length=128)),
                ('email', models.EmailField(max_length=254)),
                ('first_name', models.CharField(max_length=80)),
                ('middle_name', models.CharField(blank=True, max_length=80)),
                ('last_name', models.CharField(max_length=80)),
                ('birthdate', models.DateField()),
                ('password_hash', models.CharField(blank=True, max_length=128)),
                ('profile_image', models.TextField(blank=True)),
                ('remember', models.BooleanField(default=False)),
                ('expires_at', models.DateTimeField()),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('is_used', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account_verifications', to='accounts.patientprofile')),
            ],
            options={
                'indexes': [models.Index(fields=['patient', 'created_at'], name='patient_otp_created_idx'), models.Index(fields=['created_at'], name='patient_otp_old_idx')],
            },
        ),
    ]
