# Generated by Django 5.2.17 on 2026-10-01 09:45

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_audit_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientprofile',
            name='privacy_consent_recorded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='privacy_consent_recordings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='sms_consent_method',
            field=models.CharField(blank=True, max_length=16),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='sms_consent_recorded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sms_consent_recordings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='sms_stop_reason',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='sms_stop_reason_detail',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='auditevent',
            name='event',
            field=models.CharField(choices=[('LOGIN_SUCCESS', 'Login succeeded'), ('LOGIN_FAILED', 'Login failed'), ('LOGOUT', 'Logged out'), ('PASSWORD_CHANGED', 'Password changed'), ('ACCOUNT_LOCKED', 'Account locked'), ('ACCOUNT_DISABLED', 'Account disabled'), ('ACCOUNT_ENABLED', 'Account enabled'), ('PATIENT_CREATED', 'Patient record created'), ('PATIENT_UPDATED', 'Patient record updated'), ('PATIENT_DELETED', 'Patient record deleted'), ('SMS_CONSENT_RECORDED', 'Patient SMS choice recorded'), ('SMS_STOPPED', 'Patient SMS stopped'), ('TREATMENT_CREATED', 'Treatment record created'), ('TREATMENT_UPDATED', 'Treatment record updated'), ('TREATMENT_DELETED', 'Treatment record deleted'), ('APPOINTMENT_CANCELLED', 'Appointment cancelled'), ('SMS_SENT', 'SMS accepted by gateway')], db_index=True, max_length=32),
        ),
        migrations.CreateModel(
            name='PatientConsentRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_id_snapshot', models.CharField(db_index=True, max_length=64)),
                ('kind', models.CharField(choices=[('privacy', 'Privacy agreement'), ('sms', 'SMS messages')], max_length=8)),
                ('action', models.CharField(choices=[('recorded', 'Patient choice recorded'), ('stopped', 'SMS stopped')], max_length=8)),
                ('consent_given', models.BooleanField()),
                ('patient_choice_confirmed', models.BooleanField(default=False)),
                ('method', models.CharField(blank=True, max_length=16)),
                ('purpose', models.CharField(blank=True, max_length=200)),
                ('notice_version', models.CharField(blank=True, max_length=40)),
                ('stop_reason', models.CharField(blank=True, max_length=32)),
                ('stop_reason_detail', models.CharField(blank=True, max_length=300)),
                ('actor_id_snapshot', models.CharField(blank=True, max_length=64)),
                ('actor_role', models.CharField(blank=True, max_length=16)),
                ('recorded_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patient_consent_records', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consent_records', to='accounts.patientprofile')),
            ],
            options={
                'ordering': ['-recorded_at', '-id'],
                'indexes': [models.Index(fields=['patient', '-recorded_at'], name='consent_patient_date_idx')],
            },
        ),
    ]
