# Generated by Django 5.2.17 on 2026-10-01 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_patientprofile_privacy_consent_recorded_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientconsentrecord',
            name='consent_given',
            field=models.BooleanField(null=True),
        ),
    ]
