# Generated by Django 5.2.17 on 2026-10-06 02:16

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_patientconsentrecord_consent_given'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditevent',
            name='event',
            field=models.CharField(choices=[('LOGIN_SUCCESS', 'Login succeeded'), ('LOGIN_FAILED', 'Login failed'), ('LOGOUT', 'Logged out'), ('PASSWORD_CHANGED', 'Password changed'), ('PASSWORD_RESET', 'Password reset'), ('ACCOUNT_LOCKED', 'Account locked'), ('ACCOUNT_DISABLED', 'Account disabled'), ('ACCOUNT_ENABLED', 'Account enabled'), ('PATIENT_CREATED', 'Patient record created'), ('PATIENT_UPDATED', 'Patient record updated'), ('PATIENT_DELETED', 'Patient record deleted'), ('SMS_CONSENT_RECORDED', 'Patient SMS choice recorded'), ('SMS_STOPPED', 'Patient SMS stopped'), ('TREATMENT_CREATED', 'Treatment record created'), ('TREATMENT_UPDATED', 'Treatment record updated'), ('TREATMENT_DELETED', 'Treatment record deleted'), ('APPOINTMENT_CANCELLED', 'Appointment cancelled'), ('SMS_SENT', 'SMS accepted by gateway')], db_index=True, max_length=32),
        ),
        migrations.CreateModel(
            name='PasswordResetVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_key', models.CharField(db_index=True, max_length=64)),
                ('masked_email', models.CharField(max_length=254)),
                ('token_hash', models.CharField(max_length=64, unique=True)),
                ('code_hash', models.CharField(blank=True, max_length=256)),
                ('expires_at', models.DateTimeField()),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('is_verified', models.BooleanField(default=False)),
                ('is_used', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='password_reset_verifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['email_key', '-created_at'], name='reset_email_created_idx'), models.Index(fields=['user', '-created_at'], name='reset_user_created_idx'), models.Index(fields=['created_at'], name='reset_created_idx')],
            },
        ),
    ]
