# Generated by Django 5.2.17 on 2026-09-21 13:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('communications', '0001_initial'),
        ('records', '0001_initial'),
        ('scheduling', '0002_availabilityslot'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SmsBalanceSchedule',
            fields=[
                ('patient', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='accounts.patientprofile')),
                ('next_due_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SmsWorker',
            fields=[
                ('id', models.PositiveSmallIntegerField(default=1, primary_key=True, serialize=False)),
                ('last_run_at', models.DateTimeField(blank=True, null=True)),
                ('lease_until', models.DateTimeField(blank=True, null=True)),
                ('lease_token', models.CharField(blank=True, max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='SmsRule',
            fields=[
                ('key', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('enabled', models.BooleanField(default=True)),
                ('template', models.TextField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SmsMessage',
            fields=[
                ('id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('event_key', models.CharField(max_length=180, unique=True)),
                ('patient_name', models.CharField(max_length=120)),
                ('phone', models.CharField(blank=True, max_length=24)),
                ('body', models.TextField()),
                ('context', models.JSONField(default=dict)),
                ('is_test', models.BooleanField(default=False)),
                ('status', models.CharField(default='queued', max_length=24)),
                ('provider_id', models.CharField(blank=True, max_length=80, null=True, unique=True)),
                ('error', models.CharField(blank=True, max_length=300)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('scheduled_for', models.DateTimeField()),
                ('expires_at', models.DateTimeField()),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('checked_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('appointment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='scheduling.appointment')),
                ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.patientprofile')),
                ('record', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='records.treatmentrecord')),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='communications.smsrule')),
            ],
            options={
                'indexes': [models.Index(fields=['status', 'scheduled_for'], name='sms_queue_idx')],
            },
        ),
    ]
