# Generated by Django 5.2.17 on 2026-09-21 14:29

import django.db.models.deletion
from django.db import migrations, models


def preserve_templates(apps, schema_editor):
    Rule = apps.get_model('communications', 'SmsRule')
    Template = apps.get_model('communications', 'SmsTemplate')
    names = {
        'booking': 'Appointment Booked', 'approval': 'Appointment Approved',
        'walk_in': 'Walk-in Appointment Added', 'next_visit': 'Next Visit Reminder',
        'balance': 'Payment Reminder', 'cancellation': 'Appointment Cancelled',
    }
    alias = schema_editor.connection.alias
    for rule in Rule.objects.using(alias).all():
        template = Template.objects.using(alias).create(
            id='smst_' + rule.key, rule=rule, name=names.get(rule.key, rule.key),
            body=rule.template, delay_minutes=0,
        )
        Template.objects.using(alias).filter(pk=template.pk).update(updated_at=rule.updated_at)
        Rule.objects.using(alias).filter(pk=rule.pk).update(active_template=template)


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0002_smsbalanceschedule_smsworker_smsrule_smsmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='smsrule',
            name='delay_minutes',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='SmsTemplate',
            fields=[
                ('id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('body', models.TextField()),
                ('delay_minutes', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='templates', to='communications.smsrule')),
            ],
        ),
        migrations.AddField(
            model_name='smsrule',
            name='active_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='active_for_rules', to='communications.smstemplate'),
        ),
        migrations.RunPython(preserve_templates, migrations.RunPython.noop),
    ]
